name: Build Flutter APK

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          find . -name "pubspec.yaml" -execdir flutter pub get \;
          find . -name "pubspec.yaml" -execdir flutter build apk --debug --no-tree-shake-icons \;

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: alfaeq_yemen_app
          path: '**/*.apk'
